name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13.0.1
    - uses: actions/checkout@v1
    - name: Build with Maven
      run: mvn clean -B package --file pom.xml -Pproduction
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: my-starter-project-2.0-SNAPSHOT.jar
        path: target/my-starter-project-2.0-SNAPSHOT.jar
